# Site Settings
title: Poplar's Bluff
email: gyeosalom@gmail.com
description: A blog for Neverwinter Nights content.

# Main Directory
source: contents

# Plugins
plugins:
  - jekyll-relative-links

# Build Exclusions
exclude:
  [
    "Makefile",
    "README.md"
  ]

sass:
  quiet_deps: true

theme: "just-the-docs"
favicon_ico: "/assets/img/favicon.ico"
color_scheme: poplar

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  summary:
    color: orange
